name: Build-dictionary-image

on: [push]

jobs:
  build_docker_img:
    runs-on: ubuntu-latest
    env:
      TAG: nginx
      PAT: ${{ secrets.GITHUB_TOKEN }}
      USER: mariepad
      REGISTRY: ghcr.io
      VERSION: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build Docker Image
      run: docker build -t ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} .
    
    - name: Login to ghcr
      run: |
        echo $PAT | docker login ${{ env.REGISTRY}} -u $USER --password-stdin
        docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
